FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    build-essential \
    libbliss-dev \
    libgmp-dev \
    libhiredis-dev \
    libssl-dev \
    nlohmann-json3-dev

WORKDIR /build
